#!/usr/bin/env bash
# <FILE>scripts/k219_visual_demo.sh</FILE> - <DESC>K2.19 compositor playback and studio-control demo harness</DESC>
# <VERS>VERSION: 0.1.0</VERS>
# <WCTX>K2.19 visual playback: generate visible artifacts for compositor backend and studio control pilot.</WCTX>
# <CLOG>0.1.0: INIT — render debug recipes, ANSI snapshots, timeline samples, and studio before/after hashes.</CLOG>
set -euo pipefail

RECIPE_REPO="${RECIPE_REPO:-/usr/projects/tui-vfx-recipes}"
OUT_DIR="${OUT_DIR:-/tmp/k219-visual-results}"
DESCRIPTOR_PACK="${DESCRIPTOR_PACK:-descriptors/v3.1/packs/primitive.json}"
ROOT="$RECIPE_REPO/recipes/v3.1/debug_recipes"
mkdir -p "$OUT_DIR"

run_backend_json() {
  local name="$1"
  local recipe="$2"
  cargo run -q -p tui-vfx-player-cli -- render-backend \
    --descriptor-pack "$DESCRIPTOR_PACK" \
    --backend compositor \
    --format json \
    --recipe "$ROOT/$recipe" \
    > "$OUT_DIR/$name.json"
  jq -e '.backend == "compositor" and (.backendHash > 0)' "$OUT_DIR/$name.json" >/dev/null
}

run_backend_ansi() {
  local name="$1"
  local recipe="$2"
  cargo run -q -p tui-vfx-player-cli -- render-backend \
    --descriptor-pack "$DESCRIPTOR_PACK" \
    --backend compositor \
    --format ansi \
    --recipe "$ROOT/$recipe" \
    > "$OUT_DIR/$name.ansi"
  grep -q $'\033\[38;2;' "$OUT_DIR/$name.ansi" || grep -q $'\033\[48;2;' "$OUT_DIR/$name.ansi"
}

run_playback() {
  local name="$1"
  local recipe="$2"
  cargo run -q -p tui-vfx-player-cli -- play-backend \
    --descriptor-pack "$DESCRIPTOR_PACK" \
    --backend compositor \
    --format ansi \
    --frames 5 \
    --fps 20 \
    --duration-ms 1000 \
    --sample-ms 0 \
    --no-clear \
    --recipe "$ROOT/$recipe" \
    > "$OUT_DIR/$name.play.ansi"
  grep -q 'frame: 0' "$OUT_DIR/$name.play.ansi"
  grep -q 'frame: 1' "$OUT_DIR/$name.play.ansi"
}

run_playback_color() {
  run_playback "$1" "$2"
  grep -q $'\033\[38;2;' "$OUT_DIR/$1.play.ansi" || grep -q $'\033\[48;2;' "$OUT_DIR/$1.play.ansi"
}

run_timeline() {
  local name="$1"
  local recipe="$2"
  cargo run -q -p tui-vfx-player-cli -- render-backend-timeline \
    --descriptor-pack "$DESCRIPTOR_PACK" \
    --backend compositor \
    --format json \
    --samples 5 \
    --sample-ms 250 \
    --recipe "$ROOT/$recipe" \
    > "$OUT_DIR/$name.timeline.json"
  jq -e '.samples | length == 5' "$OUT_DIR/$name.timeline.json" >/dev/null
  jq -e '.sampleMs == 250 and [.samples[].sample.phaseT] == [0, 0.25, 0.5, 0.75, 1]' "$OUT_DIR/$name.timeline.json" >/dev/null
  jq -e '[.samples[].backendHash] | unique | length > 1' "$OUT_DIR/$name.timeline.json" >/dev/null
}

run_studio() {
  local name="$1"
  local recipe="$2"
  local assignment="$3"
  cargo run -q -p tui-vfx-player-cli -- studio-snapshot \
    --descriptor-pack "$DESCRIPTOR_PACK" \
    --backend compositor \
    --recipe "$ROOT/$recipe" \
    --set "$assignment" \
    --json \
    > "$OUT_DIR/$name.studio.json"
  jq -e '.beforeBackendHash != .afterBackendHash and .changedCells > 0' "$OUT_DIR/$name.studio.json" >/dev/null
}

run_backend_json baseline baseline.json
run_backend_json filter_tint filters/filter_tint.json
run_backend_json mask_wipe masks/mask_wipe.json
run_backend_json mask_checkers masks/mask_checkers.json
run_backend_json gradient_apply shaders/primitives/shader_linear_gradient_apply_to_both.json
run_backend_json gradient_diagonal shaders/primitives/shader_linear_gradient_diagonal.json
run_backend_json border_sweep shaders/compositions/shader_border_sweep_position_binding.json
run_backend_json style_modulo styles/style_modulo_horizontal_every_third_row.json

run_backend_ansi gradient_apply shaders/primitives/shader_linear_gradient_apply_to_both.json
run_backend_ansi filter_tint filters/filter_tint.json
run_backend_ansi border_sweep shaders/compositions/shader_border_sweep_position_binding.json

run_playback live_mask_wipe masks/mask_wipe.json
run_playback_color live_color_motion styles/style_fade_in_from_canvas.json
run_playback_color live_gradient shaders/primitives/shader_linear_gradient_apply_to_both.json

run_timeline mask_checkers masks/mask_checkers.json
run_timeline mask_wipe masks/mask_wipe.json

run_studio studio_border_sweep shaders/compositions/shader_border_sweep_position_binding.json sweep_progress=0.75
run_studio studio_pill_button filters/filter_pill_button_progress_binding.json demo_progress=1.0

cargo run -q -p tui-vfx-player-ui -- \
  --descriptor-pack "$DESCRIPTOR_PACK" \
  --recipes-root "$ROOT" \
  --recipe "$ROOT/shaders/primitives/shader_linear_gradient_apply_to_both.json" \
  --backend compositor \
  --once \
  --no-clear \
  > "$OUT_DIR/ui_gradient_once.txt"

grep -q 'backend: compositor' "$OUT_DIR/ui_gradient_once.txt"


cat > "$OUT_DIR/README.md" <<README
# K2.19 visual playback artifacts

Generated by ./scripts/k219_visual_demo.sh.

Live playback commands are captured in:
- $OUT_DIR/live_mask_wipe.play.ansi
- $OUT_DIR/live_color_motion.play.ansi
- $OUT_DIR/live_gradient.play.ansi

To see actual in-place terminal playback, run without --no-clear and without --sample-ms 0, for example:

    cargo run -q -p tui-vfx-player-cli -- play-backend --descriptor-pack $DESCRIPTOR_PACK --backend compositor --format ansi --fps 12 --duration-ms 2000 --recipe $ROOT/styles/style_fade_in_from_canvas.json
README

cat <<TABLE
result|artifact|pass/fail
compositor baseline|$OUT_DIR/baseline.json|PASS
compositor filter tint|$OUT_DIR/filter_tint.json|PASS
compositor mask wipe|$OUT_DIR/mask_wipe.json|PASS
compositor mask checkers|$OUT_DIR/mask_checkers.json|PASS
compositor gradient apply|$OUT_DIR/gradient_apply.json|PASS
compositor gradient diagonal|$OUT_DIR/gradient_diagonal.json|PASS
compositor border sweep|$OUT_DIR/border_sweep.json|PASS
compositor style modulo|$OUT_DIR/style_modulo.json|PASS
ansi gradient|$OUT_DIR/gradient_apply.ansi|PASS
ansi tint|$OUT_DIR/filter_tint.ansi|PASS
ansi border sweep|$OUT_DIR/border_sweep.ansi|PASS
live playback mask wipe|$OUT_DIR/live_mask_wipe.play.ansi|PASS
live playback color motion|$OUT_DIR/live_color_motion.play.ansi|PASS
live playback gradient color|$OUT_DIR/live_gradient.play.ansi|PASS
timeline mask checkers|$OUT_DIR/mask_checkers.timeline.json|PASS
timeline mask wipe|$OUT_DIR/mask_wipe.timeline.json|PASS
studio border sweep slider|$OUT_DIR/studio_border_sweep.studio.json|PASS
studio pill progress|$OUT_DIR/studio_pill_button.studio.json|PASS
ui compositor once|$OUT_DIR/ui_gradient_once.txt|PASS
artifact README|$OUT_DIR/README.md|PASS
TABLE

# <FILE>scripts/k219_visual_demo.sh</FILE> - <DESC>K2.19 compositor playback and studio-control demo harness</DESC>
# <VERS>END OF VERSION: 0.1.0</VERS>
