// <FILE>xtask/src/docs/gen_signals_markdown.rs</FILE> - <DESC>Generate docs/generated/SIGNALS_REFERENCE.md from merged signal data</DESC>
// <VERS>VERSION: 0.2.0</VERS>
// <WCTX>Phase α + β: signal-facade — signals pipeline markdown generator</WCTX>
// <CLOG>0.2.0: resolve OUTPUT_PATH via CARGO_MANIFEST_DIR/.. so generate_writes_to_disk passes under `cargo test -p xtask` (CWD = xtask) without breaking `cargo xtask` (CWD = workspace root)</CLOG>

use super::extract_signals_rustdoc::SignalFamily;
use super::merge_signals::{MergedSignal, MergedSignals};
use anyhow::Result;
use std::fs;
use std::path::PathBuf;

const OUTPUT_PATH: &str = "docs/generated/SIGNALS_REFERENCE.md";

/// Resolve `OUTPUT_PATH` against the workspace root so this works under both
/// `cargo xtask` (CWD = workspace root) and `cargo test -p xtask` (CWD =
/// `xtask/`).
fn output_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("CARGO_MANIFEST_DIR (xtask/) always has a parent (workspace root)")
        .join(OUTPUT_PATH)
}

/// Write the generated SIGNALS_REFERENCE.md to disk.
pub fn generate(merged: &MergedSignals) -> Result<()> {
    let content = render(merged)?;
    fs::write(output_path(), &content)?;
    Ok(())
}

/// Render the SIGNALS_REFERENCE.md content as a String (without writing to disk).
///
/// Separated from `generate()` so `docs::check()` can compare rendered output
/// against the on-disk file without regenerating (per the mod.rs pattern).
pub fn render(merged: &MergedSignals) -> Result<String> {
    let mut out = String::with_capacity(64 * 1024);

    // Autogen banner + OFPF metadata envelope.
    out.push_str("<!-- DO NOT EDIT - This file is generated by `cargo xtask docs signals` -->\n");
    out.push_str("<!-- Edit docs/templates/signals.toml or source rustdoc in mixed-signals/src/ instead -->\n");
    out.push('\n');
    out.push_str(&format!(
        "<!-- <FILE>{OUTPUT_PATH}</FILE> - <DESC>Recipe-author signal reference for mixed-signals primitives</DESC> -->\n"
    ));
    out.push_str(&format!(
        "<!-- <VERS>VERSION: {}</VERS> -->\n",
        merged.version
    ));
    out.push('\n');

    // Document title and intro.
    out.push_str("# tui-vfx Signals Reference\n\n");
    out.push_str(
        "Recipe-author cheatsheet for the mixed-signals palette reachable through \
         `SignalSpec` JSON deserialization. The **Core 12** list at the top is the \
         recommended starting point. Per-family sections below document every \
         signal primitive available.\n\n"
    );

    // Spring-channel split global notice.
    out.push_str("> **Note on physics signals.** `DampedSpring` and the other physics \
         primitives are in the *parallel motion-spec channel* — they are not reachable \
         through `SignalSpec` JSON today. They are documented below with a callout. \
         Phase γ of the signal-facade roadmap will collapse this gap.\n\n");

    out.push_str("---\n\n");

    // Table of Contents.
    out.push_str("## Table of Contents\n\n");
    out.push_str("1. [Core 12 — start here](#core-12--start-here)\n");
    for (offset, family) in ordered_families().into_iter().enumerate() {
        let toc_n = offset + 2;
        let heading = family.heading();
        let anchor = family.anchor();
        out.push_str(&format!("{toc_n}. [{heading}](#{anchor})\n"));
    }
    out.push('\n');
    out.push_str("---\n\n");

    // Core 12 cheatsheet section (Phase β deliverable).
    render_core_12(&mut out, &merged.core_12);

    // Per-family full catalog sections.
    for family in ordered_families() {
        if let Some(signals) = merged.by_family.get(&family) {
            if signals.is_empty() {
                continue;
            }
            render_family_section(&mut out, family, signals);
        }
    }

    // Metadata footer.
    out.push_str(&format!(
        "\n<!-- <FILE>{OUTPUT_PATH}</FILE> - <DESC>Recipe-author signal reference for mixed-signals primitives</DESC> -->\n"
    ));
    out.push_str(&format!(
        "<!-- <VERS>END OF VERSION: {}</VERS> -->\n",
        merged.version
    ));

    Ok(out)
}

/// Render the "Core 12 — start here" cheatsheet table.
fn render_core_12(out: &mut String, core_12: &[MergedSignal]) {
    out.push_str("## Core 12 — start here\n\n");
    out.push_str(
        "The twelve highest-leverage signals for recipe authoring. \
         Pick from this list first; everything else is in the per-family sections below.\n\n"
    );

    out.push_str("| # | Signal | One-line summary | JSON type |\n");
    out.push_str("|---|--------|------------------|-----------|\n");

    for (i, signal) in core_12.iter().enumerate() {
        let n = i + 1;
        // Use display_discriminant (editorial name, e.g. "spring" not "damped_spring").
        let discriminant = &signal.display_discriminant;
        let json_type = if signal.doc.is_parallel_channel {
            // Show the struct-level key for the JSON shape note.
            format!("{} (parallel channel)", discriminant)
        } else {
            discriminant.clone()
        };
        let summary = if signal.doc.is_parallel_channel {
            format!("{} *(parallel physics channel — see callout below)*", signal.doc.summary)
        } else {
            signal.doc.summary.clone()
        };
        out.push_str(&format!(
            "| {n} | **{discriminant}** | {summary} | `{json_type}` |\n"
        ));
    }
    out.push('\n');

    // Per-entry cheatsheet detail blocks.
    for (i, signal) in core_12.iter().enumerate() {
        let n = i + 1;
        render_core_12_entry(out, n, signal);
    }

    out.push_str("---\n\n");
}

/// Render a single Core 12 detail block (expanded version with JSON snippet + hints).
fn render_core_12_entry(out: &mut String, n: usize, signal: &MergedSignal) {
    // Use display_discriminant for the heading so "spring" appears, not "damped_spring".
    let discriminant = &signal.display_discriminant;
    out.push_str(&format!("### {n}. {discriminant}\n\n"));

    // Summary.
    if !signal.doc.summary.is_empty() {
        out.push_str(&signal.doc.summary);
        out.push_str("\n\n");
    }

    // Physics-channel callout if applicable.
    if signal.doc.is_parallel_channel {
        out.push_str(
            "> **Parallel channel.** This signal (`DampedSpring`) is NOT reachable through \
             `SignalSpec` JSON today — it lives in the parallel motion-spec channel. \
             Phase γ will collapse this gap. For now, use it via the effect-spec's \
             motion-spec field. The JSON shape is the struct's serde field layout below.\n\n"
        );
    }

    // JSON example.
    out.push_str("```jsonc\n");
    out.push_str(&signal.example_json);
    out.push('\n');
    out.push_str("```\n\n");

    // Editorial hint + use cases.
    if let Some(editorial) = &signal.editorial {
        if let Some(hint) = &editorial.recipe_hint {
            out.push_str("**Recipe hint:** ");
            out.push_str(hint.trim());
            out.push_str("\n\n");
        }
        if !editorial.use_cases.is_empty() {
            out.push_str(&format!(
                "**Use cases:** {}\n\n",
                editorial.use_cases.join(", ")
            ));
        }
    }
}

/// Render a full family section with per-signal detail entries.
fn render_family_section(out: &mut String, family: SignalFamily, signals: &[MergedSignal]) {
    let heading = family.heading();
    let anchor = family.anchor();
    out.push_str(&format!("## {heading} {{#{anchor}}}\n\n"));

    // Family-level intro for the physics section (spring-channel callout).
    if family == SignalFamily::Physics {
        out.push_str(
            "> **Physics channel note.** Physics signals (`DampedSpring`, `BouncingDrop`, etc.) \
             are NOT reachable through `SignalSpec` JSON deserialization today. They live in the \
             parallel motion-spec channel and are instantiated via effect-spec fields rather than \
             signal graphs. They are documented here for completeness. \
             Phase γ of the signal-facade roadmap will make them first-class `SignalSpec` variants.\n\n"
        );
    }

    for signal in signals {
        render_signal_entry(out, signal);
    }
}

/// Render a single signal entry in the full catalog.
fn render_signal_entry(out: &mut String, signal: &MergedSignal) {
    let discriminant = &signal.doc.discriminant;
    out.push_str(&format!("### {discriminant}\n\n"));

    // Parallel channel callout (for physics primitives).
    if signal.doc.is_parallel_channel {
        out.push_str(
            "*Parallel physics channel — not a `SignalSpec` variant today. \
             See family note above. Phase γ will promote these to `SignalSpec`.*\n\n"
        );
    }

    // Summary + full description.
    if !signal.doc.summary.is_empty() {
        out.push_str(&signal.doc.summary);
        out.push('\n');
    }
    if !signal.doc.description.is_empty()
        && signal.doc.description != signal.doc.summary
    {
        out.push('\n');
        // Remaining description lines after the summary.
        let rest: String = signal
            .doc
            .description
            .lines()
            .skip(1)
            .map(|l| format!("{l}\n"))
            .collect();
        if !rest.trim().is_empty() {
            out.push_str(&rest);
        }
    }
    out.push('\n');

    // Field table (skip for unit variants / empty field list).
    if !signal.doc.fields.is_empty() {
        out.push_str("| Field | Type | Description |\n");
        out.push_str("|-------|------|-------------|\n");
        for field in &signal.doc.fields {
            let doc = if field.doc.is_empty() { "—" } else { &field.doc };
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                field.name, field.ty, doc
            ));
        }
        out.push('\n');
    }

    // JSON example.
    if !signal.doc.is_parallel_channel {
        out.push_str("```jsonc\n");
        out.push_str(&signal.example_json);
        out.push('\n');
        out.push_str("```\n\n");
    } else {
        out.push_str("*Use via the effect-spec motion field. JSON shape corresponds to struct fields above.*\n\n");
    }

    // Editorial hint + use cases (if present).
    if let Some(editorial) = &signal.editorial {
        if let Some(hint) = &editorial.recipe_hint {
            out.push_str("**Recipe hint:** ");
            out.push_str(hint.trim());
            out.push_str("\n\n");
        }
        if !editorial.use_cases.is_empty() {
            out.push_str(&format!(
                "**Use cases:** {}\n\n",
                editorial.use_cases.join(", ")
            ));
        }
    }
}

/// Return SignalFamily variants in the order they appear in the generated document.
fn ordered_families() -> Vec<SignalFamily> {
    vec![
        SignalFamily::Oscillator,
        SignalFamily::Spatial,
        SignalFamily::Envelope,
        SignalFamily::Physics,
        SignalFamily::Noise,
        SignalFamily::Composition,
        SignalFamily::Processing,
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::{extract_signals_rustdoc, merge_signals, parse_signals_toml};

    fn make_merged() -> MergedSignals {
        let rustdoc = extract_signals_rustdoc::extract().expect("extraction failed");
        let toml = parse_signals_toml::parse().expect("parse failed");
        merge_signals::merge(rustdoc, toml).expect("merge failed")
    }

    #[test]
    fn render_produces_core_12_section() {
        let merged = make_merged();
        let output = render(&merged).expect("render failed");
        assert!(
            output.contains("## Core 12 — start here"),
            "Output should contain the Core 12 section heading"
        );
        assert!(
            output.contains("sine"),
            "Core 12 section should mention sine"
        );
    }

    #[test]
    fn render_contains_family_sections() {
        let merged = make_merged();
        let output = render(&merged).expect("render failed");
        assert!(output.contains("## Oscillators"), "should have Oscillators section");
        assert!(output.contains("## Envelopes"), "should have Envelopes section");
        assert!(output.contains("## Physics"), "should have Physics section");
    }

    #[test]
    fn render_documents_spring_channel_split() {
        let merged = make_merged();
        let output = render(&merged).expect("render failed");
        assert!(
            output.contains("parallel") && output.contains("DampedSpring"),
            "Output should document the DampedSpring parallel-channel split"
        );
    }

    #[test]
    fn generate_writes_to_disk() {
        let merged = make_merged();
        generate(&merged).expect("generate failed");
        let content = std::fs::read_to_string(output_path()).expect("output file should exist");
        assert!(!content.is_empty(), "generated file should be non-empty");
        assert!(
            content.contains("Core 12"),
            "generated file should contain Core 12 section"
        );
    }
}

// <FILE>xtask/src/docs/gen_signals_markdown.rs</FILE> - <DESC>Generate docs/generated/SIGNALS_REFERENCE.md from merged signal data</DESC>
// <VERS>END OF VERSION: 0.2.0</VERS>
