// <FILE>xtask/src/docs/gen_markdown.rs</FILE> - <DESC>Generate CAPABILITIES.md from merged data</DESC>
// <VERS>VERSION: 1.1.1</VERS>
// <WCTX>Address clippy single_char_add_str warnings</WCTX>
// <CLOG>Use push('\\n') for single-character newlines</CLOG>

use super::merge::MergedManifest;
use anyhow::{Context, Result};
use std::fs;

const OUTPUT_DIR: &str = "docs/generated";
const OUTPUT_PATH: &str = "docs/generated/CAPABILITIES.md";

/// Generate CAPABILITIES.md from merged manifest.
pub fn generate(manifest: &MergedManifest) -> Result<()> {
    let output = render(manifest)?;

    // Ensure output directory exists
    fs::create_dir_all(OUTPUT_DIR).with_context(|| format!("Failed to create {}", OUTPUT_DIR))?;

    // Write file
    fs::write(OUTPUT_PATH, &output).with_context(|| format!("Failed to write {}", OUTPUT_PATH))?;

    Ok(())
}

/// Render CAPABILITIES.md content without writing to disk.
pub fn render(manifest: &MergedManifest) -> Result<String> {
    let mut output = String::new();

    // Header
    output
        .push_str("<!-- DO NOT EDIT - This file is generated by `cargo xtask docs generate` -->\n");
    output.push_str(
        "<!-- Edit docs/templates/capabilities.toml or source rustdoc comments instead -->\n\n",
    );
    output.push_str(&format!(
        "<!-- <FILE>{}</FILE> - <DESC>Comprehensive inventory of tui-vfx visual effects capabilities</DESC> -->\n",
        OUTPUT_PATH
    ));
    output.push_str(&format!(
        "<!-- <VERS>VERSION: {}</VERS> -->\n\n",
        manifest.version
    ));

    output.push_str("# tui-vfx Capabilities Reference\n\n");
    output.push_str(
        "This document provides a complete inventory of visual effects available in tui-vfx.\n\n",
    );

    // Table of Contents
    output.push_str("---\n\n");
    output.push_str("## Table of Contents\n\n");
    output.push_str("1. [Masks (Transition Shapes)](#masks-transition-shapes)\n");
    output.push_str("2. [Filters (Post-Processing)](#filters-post-processing)\n");
    output.push_str("3. [Samplers (Coordinate Distortion)](#samplers-coordinate-distortion)\n");
    output.push_str("4. [Spatial Shaders (Per-Cell Styling)](#spatial-shaders-per-cell-styling)\n");
    output
        .push_str("5. [Style Effects (Temporal Animations)](#style-effects-temporal-animations)\n");
    output
        .push_str("6. [Content Transformers (Text Effects)](#content-transformers-text-effects)\n");
    output.push_str("7. [Shadows](#shadows)\n");
    output.push_str("8. [Quick Reference](#quick-reference)\n\n");

    // Generate each section
    output.push_str("---\n\n");
    generate_effects_section(
        &mut output,
        "Masks (Transition Shapes)",
        &manifest.effects.masks,
    );
    generate_effects_section(
        &mut output,
        "Filters (Post-Processing)",
        &manifest.effects.filters,
    );
    generate_effects_section(
        &mut output,
        "Samplers (Coordinate Distortion)",
        &manifest.effects.samplers,
    );
    generate_effects_section(
        &mut output,
        "Spatial Shaders (Per-Cell Styling)",
        &manifest.effects.shaders,
    );
    generate_effects_section(
        &mut output,
        "Style Effects (Temporal Animations)",
        &manifest.effects.styles,
    );
    generate_effects_section(
        &mut output,
        "Content Transformers (Text Effects)",
        &manifest.effects.content,
    );
    generate_effects_section(&mut output, "Shadows", &manifest.effects.shadows);

    // Quick Reference from semantics
    output.push_str("## Quick Reference\n\n");
    generate_quick_reference(&mut output, manifest);

    // Footer
    output.push_str(&format!(
        "\n<!-- <FILE>{}</FILE> - <DESC>Comprehensive inventory of tui-vfx visual effects capabilities</DESC> -->\n",
        OUTPUT_PATH
    ));
    output.push_str(&format!(
        "<!-- <VERS>END OF VERSION: {}</VERS> -->\n",
        manifest.version
    ));

    Ok(output)
}

fn generate_effects_section(
    output: &mut String,
    title: &str,
    effects: &std::collections::HashMap<String, super::merge::MergedEffect>,
) {
    output.push_str(&format!("## {}\n\n", title));

    if effects.is_empty() {
        output.push_str("*No effects documented yet.*\n\n");
        return;
    }

    // Table header
    output.push_str("| Effect | Description | Use Cases |\n");
    output.push_str("|--------|-------------|----------|\n");

    // Sort effects by name for consistent output
    let mut sorted: Vec<_> = effects.iter().collect();
    sorted.sort_by_key(|(name, _)| name.as_str());

    for (name, effect) in sorted {
        let description = effect
            .rustdoc_summary
            .as_deref()
            .filter(|s| !s.is_empty())
            .or(Some(&effect.ai_hint))
            .unwrap_or("-");

        let use_cases = if effect.use_cases.is_empty() {
            "-".to_string()
        } else {
            effect.use_cases.join(", ")
        };

        output.push_str(&format!(
            "| **{}** | {} | {} |\n",
            name, description, use_cases
        ));
    }

    output.push('\n');
}

fn generate_quick_reference(output: &mut String, manifest: &MergedManifest) {
    if !manifest.semantics.use_cases.is_empty() {
        output.push_str("### Effect Categories by Use Case\n\n");

        let mut sorted: Vec<_> = manifest.semantics.use_cases.iter().collect();
        sorted.sort_by_key(|(name, _)| name.as_str());

        for (use_case, mapping) in sorted {
            output.push_str(&format!("**{}**:\n", use_case));

            if !mapping.masks.is_empty() {
                output.push_str(&format!("- Masks: {}\n", mapping.masks.join(", ")));
            }
            if !mapping.filters.is_empty() {
                output.push_str(&format!("- Filters: {}\n", mapping.filters.join(", ")));
            }
            if !mapping.shaders.is_empty() {
                output.push_str(&format!("- Shaders: {}\n", mapping.shaders.join(", ")));
            }
            if !mapping.content.is_empty() {
                output.push_str(&format!("- Content: {}\n", mapping.content.join(", ")));
            }

            output.push('\n');
        }
    }

    if !manifest.semantics.moods.is_empty() {
        output.push_str("### Effects by Mood\n\n");

        let mut sorted: Vec<_> = manifest.semantics.moods.iter().collect();
        sorted.sort_by_key(|(name, _)| name.as_str());

        for (mood, effects) in sorted {
            output.push_str(&format!("- **{}**: {}\n", mood, effects.join(", ")));
        }

        output.push('\n');
    }
}

// <FILE>xtask/src/docs/gen_markdown.rs</FILE> - <DESC>Generate CAPABILITIES.md from merged data</DESC>
// <VERS>END OF VERSION: 1.1.1</VERS>
