// <FILE>xtask/src/docs/gen_signals_markdown.rs</FILE> - <DESC>Generate docs/generated/API_SIGNALS_REFERENCE.md (engine / direct-API audience) from merged signal data</DESC>
// <VERS>VERSION: 0.3.0</VERS>
// <WCTX>Packet 67 — engine/API doc relabel: rename output to API_SIGNALS_REFERENCE.md, rescope to direct-API consumers, emit "wrong door" preamble pointing recipe authors at the recipe-side reference, drop the post-Phase-A stale physics-callout emission</WCTX>
// <CLOG>0.3.0: rename OUTPUT_PATH to API_SIGNALS_REFERENCE.md; add PREAMBLE const + emit it above the autogen banner; H1 → "Engine / Direct-API Signals Reference"; drop the "Note on physics signals" callout, the Core 12 (parallel channel) annotation, the Physics-section family intro callout, and the per-entry parallel-channel line; render JSON example unconditionally</CLOG>

use super::extract_signals_rustdoc::SignalFamily;
use super::merge_signals::{MergedSignal, MergedSignals};
use anyhow::Result;
use std::fs;
use std::path::PathBuf;

const OUTPUT_PATH: &str = "docs/generated/API_SIGNALS_REFERENCE.md";

/// Engine / direct-API audience marker. Emitted at the very top of the rendered
/// document so a reader hitting the page from a recipe-author search sees it
/// before the autogen banner or any catalog content.
///
/// Symmetric companion: tui-vfx-recipes/docs/generated/RECIPE_SIGNALS_REFERENCE.md
/// carries an inverted preamble pointing back at this file for engine-API
/// consumers who land there by mistake (Packet 01 in the recipes repo owns it).
const PREAMBLE: &str = "> **⚠ Not for recipe authors.**\n\
    >\n\
    > This reference documents `mixed_signals::*` primitives as reached by\n\
    > **direct API construction** in engine code (`tui-vfx-content`, `tui-vfx-style`,\n\
    > `gt-design` motion runtime, and other `mixed_signals::*` consumers).\n\
    >\n\
    > If you are writing a recipe JSON file (anything with `\"type\": \"sine\"`,\n\
    > `\"type\": \"spring\"`, `\"signal\": {...}`, etc.), **stop reading this document**\n\
    > and go to:\n\
    >\n\
    >   **→ `tui-vfx-recipes/docs/generated/RECIPE_SIGNALS_REFERENCE.md`**\n\
    >\n\
    > The recipe-author surface is `tui_vfx_recipes::signals::VfxRecipeSignalSpec`,\n\
    > a curated, wire-format-stable facade over `mixed_signals::*`. Field shapes,\n\
    > defaults, recommended use, and Core 12 guidance are documented there in\n\
    > recipe-author terms. This document does not cover them.\n\n";

/// Resolve `OUTPUT_PATH` against the workspace root so this works under both
/// `cargo xtask` (CWD = workspace root) and `cargo test -p xtask` (CWD =
/// `xtask/`).
fn output_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("CARGO_MANIFEST_DIR (xtask/) always has a parent (workspace root)")
        .join(OUTPUT_PATH)
}

/// Write the generated API_SIGNALS_REFERENCE.md to disk.
pub fn generate(merged: &MergedSignals) -> Result<()> {
    let content = render(merged)?;
    fs::write(output_path(), &content)?;
    Ok(())
}

/// Render the API_SIGNALS_REFERENCE.md content as a String (without writing to disk).
///
/// Separated from `generate()` so `docs::signals_check()` can compare rendered
/// output against the on-disk file without regenerating (per the mod.rs pattern).
pub fn render(merged: &MergedSignals) -> Result<String> {
    let mut out = String::with_capacity(64 * 1024);

    // "Wrong door" preamble at the very top of the file so a recipe author who
    // lands here from a search sees the redirect before any catalog content.
    out.push_str(PREAMBLE);

    // Autogen banner + OFPF metadata envelope.
    out.push_str("<!-- DO NOT EDIT - This file is generated by `cargo xtask docs signals` -->\n");
    out.push_str("<!-- Edit docs/templates/signals.toml or source rustdoc in mixed-signals/src/ instead -->\n");
    out.push('\n');
    out.push_str(&format!(
        "<!-- <FILE>{OUTPUT_PATH}</FILE> - <DESC>Engine / direct-API signal reference for mixed-signals primitives</DESC> -->\n"
    ));
    out.push_str(&format!(
        "<!-- <VERS>VERSION: {}</VERS> -->\n",
        merged.version
    ));
    out.push('\n');

    // Document title and intro.
    out.push_str("# Engine / Direct-API Signals Reference\n\n");
    out.push_str(
        "Reference for `mixed_signals::*` primitives reached by direct API \
         construction in engine code. The **Core 12** list at the top is the \
         recommended starting point. Per-family sections below document every \
         signal primitive available through `SignalSpec` JSON deserialization \
         and through direct construction.\n\n",
    );

    out.push_str("---\n\n");

    // Table of Contents.
    out.push_str("## Table of Contents\n\n");
    out.push_str("1. [Core 12 — start here](#core-12--start-here)\n");
    for (offset, family) in ordered_families().into_iter().enumerate() {
        let toc_n = offset + 2;
        let heading = family.heading();
        let anchor = family.anchor();
        out.push_str(&format!("{toc_n}. [{heading}](#{anchor})\n"));
    }
    out.push('\n');
    out.push_str("---\n\n");

    // Core 12 cheatsheet section (Phase β deliverable).
    render_core_12(&mut out, &merged.core_12);

    // Per-family full catalog sections.
    for family in ordered_families() {
        if let Some(signals) = merged.by_family.get(&family) {
            if signals.is_empty() {
                continue;
            }
            render_family_section(&mut out, family, signals);
        }
    }

    // Metadata footer.
    out.push_str(&format!(
        "\n<!-- <FILE>{OUTPUT_PATH}</FILE> - <DESC>Engine / direct-API signal reference for mixed-signals primitives</DESC> -->\n"
    ));
    out.push_str(&format!(
        "<!-- <VERS>END OF VERSION: {}</VERS> -->\n",
        merged.version
    ));

    Ok(out)
}

/// Render the "Core 12 — start here" cheatsheet table.
fn render_core_12(out: &mut String, core_12: &[MergedSignal]) {
    out.push_str("## Core 12 — start here\n\n");
    out.push_str(
        "The twelve highest-leverage signals for recipe authoring. \
         Pick from this list first; everything else is in the per-family sections below.\n\n",
    );

    out.push_str("| # | Signal | One-line summary | JSON type |\n");
    out.push_str("|---|--------|------------------|-----------|\n");

    for (i, signal) in core_12.iter().enumerate() {
        let n = i + 1;
        // Use display_discriminant (editorial name, e.g. "spring" — post-Phase-A
        // this also matches the underlying SignalSpec discriminant).
        let discriminant = &signal.display_discriminant;
        let summary = &signal.doc.summary;
        out.push_str(&format!(
            "| {n} | **{discriminant}** | {summary} | `{discriminant}` |\n"
        ));
    }
    out.push('\n');

    // Per-entry cheatsheet detail blocks.
    for (i, signal) in core_12.iter().enumerate() {
        let n = i + 1;
        render_core_12_entry(out, n, signal);
    }

    out.push_str("---\n\n");
}

/// Render a single Core 12 detail block (expanded version with JSON snippet + hints).
fn render_core_12_entry(out: &mut String, n: usize, signal: &MergedSignal) {
    // Use display_discriminant — sourced from the editorial overlay, kept distinct
    // from doc.discriminant for clarity at the call site.
    let discriminant = &signal.display_discriminant;
    out.push_str(&format!("### {n}. {discriminant}\n\n"));

    // Summary.
    if !signal.doc.summary.is_empty() {
        out.push_str(&signal.doc.summary);
        out.push_str("\n\n");
    }

    // JSON example.
    out.push_str("```jsonc\n");
    out.push_str(&signal.example_json);
    out.push('\n');
    out.push_str("```\n\n");

    // Editorial hint + use cases.
    if let Some(editorial) = &signal.editorial {
        if let Some(hint) = &editorial.recipe_hint {
            out.push_str("**Recipe hint:** ");
            out.push_str(hint.trim());
            out.push_str("\n\n");
        }
        if !editorial.use_cases.is_empty() {
            out.push_str(&format!(
                "**Use cases:** {}\n\n",
                editorial.use_cases.join(", ")
            ));
        }
    }
}

/// Render a full family section with per-signal detail entries.
fn render_family_section(out: &mut String, family: SignalFamily, signals: &[MergedSignal]) {
    let heading = family.heading();
    let anchor = family.anchor();
    out.push_str(&format!("## {heading} {{#{anchor}}}\n\n"));

    for signal in signals {
        render_signal_entry(out, signal);
    }
}

/// Render a single signal entry in the full catalog.
fn render_signal_entry(out: &mut String, signal: &MergedSignal) {
    let discriminant = &signal.doc.discriminant;
    out.push_str(&format!("### {discriminant}\n\n"));

    // Summary + full description.
    if !signal.doc.summary.is_empty() {
        out.push_str(&signal.doc.summary);
        out.push('\n');
    }
    if !signal.doc.description.is_empty() && signal.doc.description != signal.doc.summary {
        out.push('\n');
        // Remaining description lines after the summary.
        let rest: String = signal
            .doc
            .description
            .lines()
            .skip(1)
            .map(|l| format!("{l}\n"))
            .collect();
        if !rest.trim().is_empty() {
            out.push_str(&rest);
        }
    }
    out.push('\n');

    // Field table (skip for unit variants / empty field list).
    if !signal.doc.fields.is_empty() {
        out.push_str("| Field | Type | Description |\n");
        out.push_str("|-------|------|-------------|\n");
        for field in &signal.doc.fields {
            let doc = if field.doc.is_empty() {
                "—"
            } else {
                &field.doc
            };
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                field.name, field.ty, doc
            ));
        }
        out.push('\n');
    }

    // JSON example.
    out.push_str("```jsonc\n");
    out.push_str(&signal.example_json);
    out.push('\n');
    out.push_str("```\n\n");

    // Editorial hint + use cases (if present).
    if let Some(editorial) = &signal.editorial {
        if let Some(hint) = &editorial.recipe_hint {
            out.push_str("**Recipe hint:** ");
            out.push_str(hint.trim());
            out.push_str("\n\n");
        }
        if !editorial.use_cases.is_empty() {
            out.push_str(&format!(
                "**Use cases:** {}\n\n",
                editorial.use_cases.join(", ")
            ));
        }
    }
}

/// Return SignalFamily variants in the order they appear in the generated document.
fn ordered_families() -> Vec<SignalFamily> {
    vec![
        SignalFamily::Oscillator,
        SignalFamily::Spatial,
        SignalFamily::Envelope,
        SignalFamily::Physics,
        SignalFamily::Noise,
        SignalFamily::Composition,
        SignalFamily::Processing,
    ]
}

#[cfg(test)]
mod tests {
    use super::super::{extract_signals_rustdoc, merge_signals, parse_signals_toml};
    use super::*;

    fn make_merged() -> MergedSignals {
        let rustdoc = extract_signals_rustdoc::extract().expect("extraction failed");
        let toml = parse_signals_toml::parse().expect("parse failed");
        merge_signals::merge(rustdoc, toml).expect("merge failed")
    }

    #[test]
    fn render_produces_core_12_section() {
        let merged = make_merged();
        let output = render(&merged).expect("render failed");
        assert!(
            output.contains("## Core 12 — start here"),
            "Output should contain the Core 12 section heading"
        );
        assert!(
            output.contains("sine"),
            "Core 12 section should mention sine"
        );
    }

    #[test]
    fn render_contains_family_sections() {
        let merged = make_merged();
        let output = render(&merged).expect("render failed");
        assert!(
            output.contains("## Oscillators"),
            "should have Oscillators section"
        );
        assert!(
            output.contains("## Envelopes"),
            "should have Envelopes section"
        );
        assert!(output.contains("## Physics"), "should have Physics section");
    }

    #[test]
    fn render_documents_engine_api_preamble() {
        let merged = make_merged();
        let output = render(&merged).expect("render failed");
        assert!(
            output.starts_with("> **⚠ Not for recipe authors.**"),
            "Output should start with the engine-API preamble"
        );
        assert!(
            output.contains("RECIPE_SIGNALS_REFERENCE.md"),
            "Preamble should redirect recipe authors to the recipes-side reference"
        );
        assert!(
            output.contains("# Engine / Direct-API Signals Reference"),
            "Document H1 should be the engine/direct-API title"
        );
        // Post-Phase-A: every stale parallel-channel claim must be gone.
        assert!(
            !output.contains("parallel motion-spec channel"),
            "Stale 'parallel motion-spec channel' phrasing must be removed"
        );
        assert!(
            !output.contains("(parallel channel)"),
            "Stale '(parallel channel)' Core 12 annotation must be removed"
        );
        assert!(
            !output.contains("Phase γ"),
            "Stale 'Phase γ will collapse this gap' phrasing must be removed"
        );
    }

    #[test]
    fn generate_writes_to_disk() {
        let merged = make_merged();
        generate(&merged).expect("generate failed");
        let content = std::fs::read_to_string(output_path()).expect("output file should exist");
        assert!(!content.is_empty(), "generated file should be non-empty");
        assert!(
            content.contains("Core 12"),
            "generated file should contain Core 12 section"
        );
    }
}

// <FILE>xtask/src/docs/gen_signals_markdown.rs</FILE> - <DESC>Generate docs/generated/API_SIGNALS_REFERENCE.md (engine / direct-API audience) from merged signal data</DESC>
// <VERS>END OF VERSION: 0.3.0</VERS>
