// <FILE>xtask/src/docs/gen_ai_context.rs</FILE> - <DESC>Generate condensed AI context prompt</DESC>
// <VERS>VERSION: 1.0.1</VERS>
// <WCTX>Address clippy single_char_add_str warnings</WCTX>
// <CLOG>Use push('\\n') for single-character newlines</CLOG>

use super::merge::MergedManifest;
use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fs;

const OUTPUT_DIR: &str = "docs/generated";
const OUTPUT_PATH: &str = "docs/generated/ai-context.md";

/// Generate condensed AI context prompt from merged manifest.
///
/// This produces a ~50-100 line document optimized for AI context windows.
/// Focus on:
/// - Layer order and composition rules
/// - Effect names with brief descriptions
/// - Mood → effect mappings
/// - Key constraints
pub fn generate(manifest: &MergedManifest) -> Result<()> {
    let output = render(manifest)?;

    // Ensure output directory exists
    fs::create_dir_all(OUTPUT_DIR).with_context(|| format!("Failed to create {}", OUTPUT_DIR))?;

    // Write file
    fs::write(OUTPUT_PATH, &output).with_context(|| format!("Failed to write {}", OUTPUT_PATH))?;

    Ok(())
}

/// Render AI context content without writing to disk.
pub fn render(manifest: &MergedManifest) -> Result<String> {
    let mut output = String::new();

    // Header
    output.push_str("# tui-vfx Effect Composition Guide\n\n");
    output.push_str("<!-- Generated by `cargo xtask docs ai-context` - Do not edit -->\n\n");

    // Layer order
    output.push_str("## Layer Order (bottom to top)\n");
    let layer_order = ["sampler", "shadow", "mask", "shader", "filter"];
    for (i, layer) in layer_order.iter().enumerate() {
        if let Some(desc) = manifest.layers.get(*layer) {
            output.push_str(&format!("{}. {} → {}\n", i + 1, layer, desc));
        }
    }
    output.push('\n');

    // Quick effect reference
    output.push_str("## Quick Effect Reference\n\n");
    generate_condensed_effects(&mut output, "Masks", &manifest.effects.masks);
    generate_condensed_effects(&mut output, "Filters", &manifest.effects.filters);
    generate_condensed_effects(&mut output, "Shaders", &manifest.effects.shaders);
    generate_condensed_effects(&mut output, "Samplers", &manifest.effects.samplers);
    generate_condensed_effects(&mut output, "Content", &manifest.effects.content);

    // Mood mappings
    if !manifest.semantics.moods.is_empty() {
        output.push_str("## Mood → Effects\n");

        let mut sorted: Vec<_> = manifest.semantics.moods.iter().collect();
        sorted.sort_by_key(|(name, _)| name.as_str());

        for (mood, effects) in sorted {
            let effects_str = effects
                .iter()
                .take(4)
                .cloned()
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!("- {}: {}\n", mood, effects_str));
        }
        output.push('\n');
    }

    // Recipes (condensed)
    if !manifest.recipes.is_empty() {
        output.push_str("## Common Recipes\n");

        let mut sorted: Vec<_> = manifest.recipes.iter().collect();
        sorted.sort_by_key(|(name, _)| name.as_str());

        for (name, recipe) in sorted.iter().take(5) {
            let effects: Vec<String> = recipe.effects.iter().map(|e| e.effect.clone()).collect();
            output.push_str(&format!(
                "- {}: {}\n",
                name.replace('_', " "),
                effects.join(" + ")
            ));
        }
        output.push('\n');
    }

    // Key constraints
    if !manifest.constraints.conflicts.is_empty()
        || !manifest.constraints.performance_notes.is_empty()
    {
        output.push_str("## Constraints\n");

        for conflict in &manifest.constraints.conflicts {
            output.push_str(&format!(
                "- Don't combine {} + {} ({})\n",
                conflict.a, conflict.b, conflict.reason
            ));
        }

        for note in manifest.constraints.performance_notes.iter().take(3) {
            output.push_str(&format!("- {}: {}\n", note.effect, note.note));
        }

        for note in manifest.constraints.terminal_compatibility.iter().take(2) {
            output.push_str(&format!("- {}: {}\n", note.effect, note.note));
        }
    }

    Ok(output)
}

fn generate_condensed_effects(
    output: &mut String,
    title: &str,
    effects: &HashMap<String, super::merge::MergedEffect>,
) {
    if effects.is_empty() {
        return;
    }

    output.push_str(&format!("### {}\n", title));

    let mut sorted: Vec<_> = effects.iter().collect();
    sorted.sort_by_key(|(name, _)| name.as_str());

    for (name, effect) in sorted {
        // Format: Name: ai_hint or summary (condensed)
        let hint = if !effect.ai_hint.is_empty() {
            // Take first sentence or first 80 chars
            let hint = &effect.ai_hint;
            if let Some(period) = hint.find('.') {
                &hint[..=period]
            } else if hint.len() > 80 {
                &hint[..80]
            } else {
                hint
            }
        } else if let Some(ref summary) = effect.rustdoc_summary {
            summary.as_str()
        } else {
            "-"
        };

        // Add energy/premium indicators
        let mut tags = Vec::new();
        if effect.premium {
            tags.push("Premium");
        }
        if effect.energy == "intense" {
            tags.push("Intense");
        }

        let tag_str = if tags.is_empty() {
            String::new()
        } else {
            format!(" [{}]", tags.join(", "))
        };

        output.push_str(&format!("- **{}**: {}{}\n", name, hint, tag_str));
    }

    output.push('\n');
}

// <FILE>xtask/src/docs/gen_ai_context.rs</FILE> - <DESC>Generate condensed AI context prompt</DESC>
// <VERS>END OF VERSION: 1.0.1</VERS>
